INSERT INTO categories(name) VALUES ('Agriculture & Livestock');
INSERT INTO categories(name) VALUES ('Food & Related Products');
INSERT INTO categories(name) VALUES ('Coffee bars; Clubs and Related services');
INSERT INTO categories(name) VALUES ('Heavy Industry');
INSERT INTO categories(name) VALUES ('Energy &amp; Raw Materials');
INSERT INTO categories(name) VALUES ('Vehicles &amp; Transport');
INSERT INTO categories(name) VALUES ('Chemical Industry');
INSERT INTO categories(name) VALUES ('Construction');
INSERT INTO categories(name) VALUES ('Public Works (Construction)');
INSERT INTO categories(name) VALUES ('Public Works (Services)');
INSERT INTO categories(name) VALUES ('Wood; Furniture and Other similar products');
INSERT INTO categories(name) VALUES ('Leather; Textile &amp; Clothing');
INSERT INTO categories(name) VALUES ('Information; Communication &amp; Technology');
INSERT INTO categories(name) VALUES ('Telecommunications Industry');
INSERT INTO categories(name) VALUES ('Photography; Printing &amp; Publishing');
INSERT INTO categories(name) VALUES ('Luxury &amp; Leisure Products');
INSERT INTO categories(name) VALUES ('Travel; Tourism &amp; Leisure');
INSERT INTO categories(name) VALUES ('Marketing; Avdertising &amp; the Media');
INSERT INTO categories(name) VALUES ('Banking; Finance &amp; Insurance');
INSERT INTO categories(name) VALUES ('Legal services');
INSERT INTO categories(name) VALUES ('Health');
INSERT INTO categories(name) VALUES ('Education');
INSERT INTO categories(name) VALUES ('Trading services');
INSERT INTO categories(name) VALUES ('Sport');
