export const ACTIONS = {
  LOGIN_USER: 'LOGIN_USER',
  REGISTER_NGO: 'REGISTER_NGO',
  REGISTER_NGO_FAIL: 'REGISTER_NGO_FAIL',
  LOADING_TRUE: 'LOADING_TRUE',
  LOADING_FALSE: 'LOADING_FALSE',
  //Login actions
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_LOADING_TRUE: 'LOGIN_LOADING_TRUE',
  LOGIN_LOADING_FALSE: 'LOGIN_LOADING_FALSE',
  //Problems actions
  FETCHING_PROBLEMS_TRUE: 'FETCHING_PROBLEMS_TRUE',
  FETCHING_PROBLEMS_FALSE: 'FETCHING_PROBLEMS_TRUE',
  FETCHING_PROBLEMS_ERROR: 'FETCHING_PROBLEMS_ERROR',
  FETCHING_PROBLEMS_SUCCESS: 'FETCHING_PROBLEMS_SUCCESS',
  //POST Problem actions
  CREATING_PROBLEMS_TRUE: 'CREATING_PROBLEMS_TRUE',
  CREATING_PROBLEMS_FALSE: 'CREATING_PROBLEMS_FALSE',
  CREATING_PROBLEMS_SUCCESS: 'CREATING_PROBLEMS_SUCCESS',
  CREATING_PROBLEMS_ERROR: 'CREATING_PROBLEMS_ERROR',
  //Image upload actions
  UPLOADING_IMAGE_TRUE: 'UPLOADING_IMAGE_TRUE',
  UPLOADING_IMAGE_FALSE: 'UPLOADING_IMAGE_FALSE',
  UPLOADING_IMAGE_SUCCESS: 'UPLOADING_IMAGE_SUCCESS',
  UPLOADING_IMAGE_FAIL: 'UPLOADING_IMAGE_FAIL',
  //Category actions
  CATEGORY_SUCCESS: 'CATEGORY_SUCCESS',
  CATEGORY_FAIL: 'CATEGORY_FAIL'
};
