export const ACTIONS = {
  LOGIN_USER: "LOGIN_USER",
  REGISTER_NGO: "REGISTER_NGO",
  REGISTER_NGO_FAIL: "REGISTER_NGO_FAIL",
  LOADING_TRUE: "LOADING_TRUE",
  LOADING_FALSE: "LOADING_FALSE",
  //Problems actions
  FETCHING_PROBLEMS_TRUE: "FETCHING_PROBLEMS_TRUE",
  FETCHING_PROBLEMS_FALSE: "FETCHING_PROBLEMS_TRUE",
  FETCHING_PROBLEMS_ERROR: "FETCHING_PROBLEMS_ERROR",
  FETCHING_PROBLEMS_SUCCESS: "FETCHING_PROBLEMS_SUCCESS",
  CREATING_PROBLEMS_TRUE: "CREATING_PROBLEMS_TRUE",
  CREATING_PROBLEMS_FALSE: "CREATING_PROBLEMS_FALSE",
  CREATING_PROBLEMS_SUCCESS: "CREATING_PROBLEMS_SUCCESS",
  CREATING_PROBLEMS_ERROR: "CREATING_PROBLEMS_ERROR"
};
